baseURL = 'https://wiki.xubuntu.org/'
languageCode = 'en-us'
title = 'Xubuntu Wiki'
theme = ['hugo-redirect', 'hugo-book']
enableGitInfo = true

[params]
  BookSection = '/'
  BookToC = true
  BookSearch = true
  BookComments = false
  BookRepo = 'https://github.com/Xubuntu/wiki.xubuntu.org'
  BookEditPath = 'edit/main'
  BookMenuBundle = false
  BookTheme = 'auto'
  BookFavicon = 'favicon.png'

[[menus.main]]
  name = 'Wiki'
  url = '/'
  weight = 10

[[menus.main]]
  name = 'xubuntu.org'
  url = 'https://xubuntu.org/'
  weight = 20

[[menus.main]]
  name = 'Download'
  url = 'https://xubuntu.org/download/'
  weight = 30

[[menus.main]]
  name = 'Support'
  url = 'https://xubuntu.org/help/'
  weight = 40

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
